# Generated by Django 2.0.2 on 2018-05-14 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('user_answer', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'entry_table',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('sex', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'MyUser',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quest', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('question_type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'question_table',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('question', 'user', 'version')},
        ),
    ]
