# Generated by Django 2.0.2 on 2018-05-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180514_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question.MyUser', to_field='username'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('question', 'username', 'version')},
        ),
        migrations.AlterModelTable(
            name='entry',
            table='user-answer',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
