# Generated by Django 2.0.2 on 2018-05-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20180515_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
