# Generated by Django 2.0.2 on 2018-06-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20180521_0200'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='user_answer',
        ),
    ]
